f1=open("abc.txt","w")
f1.write("my first file\n")
f1.write("this file\n\n")
f1.write("contain three files\n")
f1.open("abc.txt",'r')
str=f1.read()
print("read strings:",str)
f1.close()
print(f1.name,"is closed")
